os:
  - linux

dist: trusty
sudo: false
language: node_js

cache:
  yarn: true

jobs:
  include:
    - &test
      stage: test
      name: Test on Node 8
      node_js: '8'
      install:
        - yarn
      script:
        - yarn test
    - <<: *test
      name: Test on Node 10
      node_js: '10'
    - &examplephoto
      name: Example on Node 8
      stage: "[example] remote image attachments"
      node_js: '8'
      before_install:
        - cd examples/recipes-with-photos
      install:
        - yarn
      before_script:
        - cp -f ../../gatsby-node.js ./node_modules/gastby-source-airtable
      script:
        - yarn build
    - <<: *examplephoto
      name: Example on Node 10
      node_js: '10'
